package m.luigi.eliteboy.util

import kotlinx.coroutines.runBlocking
import m.luigi.eliteboy.elitedangerous.edsm.EDSMApi

val governmentTypes = arrayOf(
    "Anarchy",
    "Communism",
    "Confederacy",
    "Corporate",
    "Cooperative",
    "Democracy",
    "Dictatorship",
    "Feudal",
    "Imperial",
    "Patronage",
    "Prison Colony",
    "Theocracy",
    "Workshop",
    "None",
    "Engineer",
    "Prison"
)

val allegianceTypes = arrayOf(
    "Alliance",
    "Empire",
    "Federation",
    "Guardian",
    "Independent",
    "None",
    "Pilots Federation",
    "Pirate",
    "Thargoid"
)

val economyTypes = arrayOf(
    "Agriculture",
    "Extraction",
    "High Tech",
    "Industrial",
    "Military",
    "Prison",
    "Refinery",
    "Service",
    "Terraforming",
    "Colony",
    "Damage",
    "Repair",
    "None",
    "Rescue"
)

val securityTypes = arrayOf(
    "Low",
    "Medium",
    "High",
    "Anarchy",
    "Lawless"
)

val factionStates = EDSMApi.SearchType.values().sliceArray(21..38).map { it.type }.toTypedArray()

val shipIdToShipName = mapOf(
    "adder" to "Adder",
    "typex" to "Alliance Chieftain",
    "typex_2" to "Alliance Crusader",
    "typex_3" to "Alliance Challenger",
    "anaconda" to "Anaconda",
    "asp" to "Asp Explorer",
    "asp_scout" to "Asp Scout",
    "belugaliner" to "Beluga Liner",
    "cobramkiii" to "Cobra MkIII",
    "cobramkiv" to "Cobra MkIV",
    "diamondbackxl" to "Diamondback Explorer",
    "diamondback" to "Diamondback Scout",
    "dolphin" to "Dolphin",
    "eagle" to "Eagle",
    "federation_dropship_mkii" to "Federal Assault Ship",
    "federation_corvette" to "Federal Corvette",
    "federation_dropship" to "Federal Dropship",
    "federation_gunship" to "Federal Gunship",
    "ferdelance" to "Fer-de-Lance",
    "hauler" to "Hauler",
    "empire_trader" to "Imperial Clipper",
    "empire_courier" to "Imperial Courier",
    "cutter" to "Imperial Cutter",
    "empire_eagle" to "Imperial Eagle",
    "independant_trader" to "Keelback",
    "krait_mkii" to "Krait MkII",
    "krait_light" to "Krait Phantom",
    "mamba" to "Mamba",
    "orca" to "Orca",
    "python" to "Python",
    "sidewinder" to "Sidewinder",
    "type6" to "Type-6 Transporter",
    "type7" to "Type-7 Transporter",
    "type9" to "Type-9 Heavy",
    "type9_military" to "Type-10 Defender",
    "viper" to "Viper MkIII",
    "viper_mkiv" to "Viper MkIV",
    "vulture" to "Vulture"
)

val modulesList =
    runBlocking {
        EDSMApi.getOutfitting(3516500480).outfitting!!.map {
            if (it.sId!!.contains("armour")) {
                val c = it.sId!!.split("armour").first().removeSuffix("_")
                "${it.name!!} - ${shipIdToShipName[c]}"
            } else {
                it.name!!
            }
        }
    } as ArrayList<String>

val commoditiesList = arrayListOf(
    "Agronomic Treatment",
    "Explosives",
    "Hydrogen Fuel",
    "Hydrogen Peroxide",
    "Liquid Oxygen",
    "Mineral Oil",
    "Nerve Agents",
    "Pesticides",
    "Rockforth Fertiliser",
    "Surface Stabilisers",
    "Synthetic Reagents",
    "Water",
    "Consumer Items",
    "Clothing",
    "Consumer Technology",
    "Domestic Appliances",
    "Duradrives",
    "Evacuation Shelter",
    "Survival Equipment",
    "Foods",
    "Algae",
    "Animal Meat",
    "Coffee",
    "Fish",
    "Food Cartridges",
    "Fruit and Vegetables",
    "Grain",
    "Synthetic Meat",
    "Tea",
    "Industrial Materials",
    "Ceramic Composites",
    "CMM Composite",
    "Insulating Membrane",
    "Meta-Alloys",
    "Micro-Weave Cooling Hoses",
    "Neofabric Insulation",
    "Polymers",
    "Semiconductors",
    "Superconductors",
    "Legal Drugs",
    "Beer",
    "Bootleg Liquor",
    "Liquor",
    "Narcotics",
    "Tobacco",
    "Wine",
    "Machinery",
    "Articulation Motors",
    "Atmospheric Processors",
    "Building Fabricators",
    "Crop Harvesters",
    "Emergency Power Cells",
    "Energy Grid Assembly",
    "Exhaust Manifold",
    "Geological Equipment",
    "Heatsink Interlink",
    "HN Shock Mount",
    "Ion Distributor",
    "Magnetic Emitter Coil",
    "Marine Equipment",
    "Microbial Furnaces",
    "Mineral Extractors",
    "Modular Terminals",
    "Power Converter",
    "Power Generators",
    "Power Transfer Bus",
    "Radiation Baffle",
    "Reinforced Mounting Plate",
    "Skimmer Components",
    "Thermal Cooling Units",
    "Water Purifiers",
    "Medicines",
    "Advanced Medicines",
    "Agri-Medicines",
    "Basic Medicines",
    "Combat Stabilisers",
    "Nanomedicines",
    "Performance Enhancers",
    "Progenitor Cells",
    "Metals",
    "Aluminium",
    "Beryllium",
    "Bismuth",
    "Cobalt",
    "Copper",
    "Gallium",
    "Gold",
    "Hafnium",
    "Indium",
    "Lanthanum",
    "Lithium",
    "Osmium",
    "Palladium",
    "Platinum",
    "Praseodymium",
    "Samarium",
    "Silver",
    "Tantalum",
    "Thallium",
    "Thorium",
    "Titanium",
    "Uranium",
    "Minerals",
    "Alexandrite",
    "Bauxite",
    "Benitoite",
    "Bertrandite",
    "Bromellite",
    "Coltan",
    "Cryolite",
    "Gallite",
    "Goslarite",
    "Grandidierite",
    "Indite",
    "Jadeite",
    "Lepidolite",
    "Lithium Hydroxide",
    "Low Temperature Diamonds",
    "Methane Clathrate",
    "Methanol Monohydrate",
    "Moissanite",
    "Monazite",
    "Musgravite",
    "Painite",
    "Pyrophyllite",
    "Rhodplumsite",
    "Rutile",
    "Serendibite",
    "Taaffeite",
    "Uraninite",
    "Void Opals",
    "Salvage",
    "Ai Relics",
    "Ancient Artefact (USS Cargo)",
    "Ancient Casket",
    "Ancient Key",
    "Ancient Orb",
    "Ancient Relic",
    "Ancient Tablet",
    "Ancient Totem",
    "Ancient Urn",
    "Antimatter Containment Unit",
    "Antique Jewellery",
    "Antiquities",
    "Assault Plans",
    "Black Box (USS Cargo)",
    "Commercial Samples",
    "Damaged Escape Pod",
    "Data Core",
    "Diplomatic Bag",
    "Earth Relics",
    "Encrypted Correspondence",
    "Encrypted Data Storage",
    "Experimental Chemicals (USS Cargo)",
    "Fossil Remnants",
    "Gene Bank",
    "Geological Samples",
    "Hostage",
    "Large Survey Data Cache",
    "Military Intelligence",
    "Military Plans (USS Cargo)",
    "Mysterious Idol",
    "Occupied CryoPod",
    "Personal Effects",
    "Political Prisoner",
    "Precious Gems",
    "Prohibited Research Materials",
    "Prototype Tech (USS Cargo)",
    "Rare Artwork (USS Cargo)",
    "Rebel Transmissions (USS Cargo)",
    "Salvageable Wreckage",
    "SapCore Container",
    "Scientific Research",
    "Scientific Samples",
    "Small Survey Data Cache",
    "Space Pioneer Relics",
    "Tactical Data",
    "Technical Blueprints (USS Cargo)",
    "Thargoid Basilisk Tissue Sample",
    "Thargoid Biological Matter",
    "Thargoid Cyclops Tissue Sample",
    "Thargoid Heart",
    "Thargoid Hydra Tissue Sample",
    "Thargoid Link",
    "Thargoid Medusa Tissue Sample",
    "Thargoid Probe",
    "Thargoid Resin",
    "Thargoid Scout Tissue Sample",
    "Thargoid Sensor",
    "Thargoid Technology Samples",
    "Time Capsule",
    "Trade Data",
    "Unstable Data Core",
    "Slavery",
    "Imperial Slaves",
    "Slaves",
    "Technology",
    "Advanced Catalysers",
    "Animal Monitors",
    "Aquaponic Systems",
    "Auto-Fabricators",
    "Bioreducing Lichen",
    "Computer Components",
    "H.E. Suits",
    "Hardware Diagnostic Sensor",
    "Land Enrichment Systems",
    "Medical Diagnostic Equipment",
    "Micro Controllers",
    "Muon Imager",
    "Nanobreakers",
    "Resonating Separators",
    "Robotics",
    "Structural Regulators",
    "Telemetry Suite",
    "Textiles",
    "Conductive Fabrics",
    "Leather",
    "Military Grade Fabrics",
    "Natural Fabrics",
    "Synthetic Fabrics",
    "Waste",
    "Biowaste",
    "Chemical Waste",
    "Scrap",
    "Toxic Waste",
    "Weapons",
    "Battle Weapons",
    "Landmines",
    "Non-lethal Weapons",
    "Personal Weapons",
    "Reactive Armour"
)